### ISSUE TITLE
[Not issue] an introduction video by me

### ISSUE THREAD

**Issue by emisjerry** [HeekangPark/obsidian-hk-code-block#2]
Hi,

I recorded a YouTube video introducing your plugin, I hope Chinese users of Obsidian will know about your work.

Here is my video: https://youtu.be/MKd336sGQDA

**Comment by HeekangPark** [comment]
Thank you! I will soon add multi-line highlight feature(ex. "1-3").

**Comment by zhouxinghong** [comment]
> Hi,
> 
> I recorded a YouTube video introducing your plugin, I hope Chinese users of Obsidian will know about your work.
> 
> Here is my video: https://youtu.be/MKd336sGQDA

尊敬的老師： 
    您好！😜您製作的教學視頻很棒！我認真看了兩遍了，但是發現一個有趣的擴展就是您在視頻中能夠左右分屏同步滾動用到的是什麼擴展吖？這個擴展好喜歡哦！😊！
