### ISSUE TITLE
Add to comunity plugins

### ISSUE THREAD

**Issue by TanZng** [HeekangPark/obsidian-hk-code-block#5]
Hello! I Can't find throw community plugins search in obsidian

<img width="546" alt="Screenshot 2023-03-27 at 16 31 24" src="https://user-images.githubusercontent.com/25267490/228081641-43a62c65-7aad-48a5-8c0c-53de5a837ec6.png">

**Comment by HeekangPark** [comment]
Only examined plugins are searchable on the Community plugins tab. I believe the Obsidian team will soon examine HK Code Block and register it to the plugin list. Until then, you should manually download HK Code Block, or you may use [BRAT](https://github.com/TfTHacker/obsidian42-brat).
